webclient/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'webclient.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^yeti_client/', include('yeti_client.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

yeti_client/urls.py
from django.conf import settings
from django.conf.urls import patterns, url
import django.contrib.auth.views
from yeti_client import views

from __init__ import VERSION, CLIENT_NAME


urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^login/$', django.contrib.auth.views.login,
            {
                'template_name': 'login.html',
                'extra_context': {
                    'version': VERSION,
                    'client_name': CLIENT_NAME
                }
            }, name='login'),
        url(r'^logout/$', django.contrib.auth.views.logout_then_login, name='logout'),
        url(r'^history/$', views.history, name='history'),
        url(r'^alerts/$', views.alerts, name='alerts'),
        url(r'^settings/$', views.settings, name='settings'),
        url(r'^push_file/$', views.push_file, name='push_file'),
        url(r'^push_stix_ip/$', views.push_stix_ip, name='push_stix_ip'),
        url(r'^push_stix_email/$', views.push_stix_email, name='push_stix_email'),
        url(r'^pull/$', views.pull, name='pull'),
        (r'^received/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT + 'received/'}),
)

yeti_client/forms.py
import os, logging, string

from django import forms
from django.template.loader import render_to_string
from django.core.validators import RegexValidator

from models import Config

from email.mime.nonmultipart import MIMENonMultipart
from email.encoders import encode_base64

import libtaxii as t
import libtaxii.messages_11 as tm11


logger = logging.getLogger(__name__)

class ConfigForm(forms.ModelForm):
    class Meta:
        model = Config
        exclude = [ 'polling', 'poll_req_tstamp', 'poll_resp_tstamp' ]

class PushFileForm(forms.Form):
    content_file = forms.FileField(label='Please select file:')

    def get_content_block(self, f):
        binding_map = {
            '.xlsx': ('application', 'vnd.openxmlformats-officedocument.spreadsheetml.sheet'),
            '.xls': ('application', 'vnd.ms-excel'),
            '.csv': ('text', 'csv'),
            '.json': ('application', 'json'),
            '.syslog': ('text', 'syslog')
        }

        # Check the file extension to see if it is a supported type
        name_part, ext_part = os.path.splitext(f.name)

        if ext_part.lower() == '.xml':
            cb = tm11.ContentBlock(tm11.ContentBinding(t.CB_STIX_XML_101), f.read())
        else:
            binding_tuple = binding_map.get(ext_part.lower(), None)
            if not binding_tuple:
                logger.error('File extension not supported: %s. Supported extensions: %s' % (ext_part, binding_map.keys()))
                return

            # Read the file and create a MIME message for it
            maintype = binding_tuple[0]
            subtype = binding_tuple[1] # Note: This is MIME subtype, not TAXII subtype
            mime_msg = MIMENonMultipart(maintype, subtype)
            mime_msg.add_header('Content-Disposition', 'attachment', filename=f.name)
            mime_msg.set_payload(f.read())
            encode_base64(mime_msg)

            cb = tm11.ContentBlock('%s/%s' % (maintype, subtype), mime_msg.as_string())

        return cb

class PushStixIPForm(forms.Form):
    ip_list = forms.CharField(label='Value',
                              max_length=255,
                              validators=[RegexValidator(regex='^(([12]?[0-9]{1,2}\.){3}[0-9]{1,3}[;,]?\s*)+$', message='Value must be comma or semicolon separated IPs')])
    desc = forms.CharField(label='Description', max_length=512, required=False)

    def get_content_block(self):
        stix_ip_list = self.cleaned_data['ip_list']
        stix_ip_list = string.replace(stix_ip_list, ",", "##comma##")
        stix_ip_list = string.replace(stix_ip_list, ";", "##comma##")
        stix_ip_list = string.replace(stix_ip_list, " ", "")
        xml = render_to_string('stix-ip-list.xml',
                               {
                                   'stix_ip_list': stix_ip_list,
                                   'description' : self.cleaned_data['desc']
                                })
        cb = tm11.ContentBlock(t.CB_STIX_XML_101, xml)
        return cb

class PushStixEmailForm(forms.Form):
    email_list = forms.CharField(label='Value',
                              max_length=255,
                              validators=[RegexValidator(regex='^([a-zA-Z0-9_.+-]+@[a-zA-Z0-9-.]+[;,]?\s*)+$', message='Value must be comma or semicolon separated E-mails')])
    desc = forms.CharField(label='Description', max_length=512, required=False)

    def get_content_block(self):
        stix_email_list = self.cleaned_data['email_list']
        stix_email_list = string.replace(stix_email_list, ",", "##comma##")
        stix_email_list = string.replace(stix_email_list, ";", "##comma##")
        stix_email_list = string.replace(stix_email_list, " ", "")
        xml = render_to_string('stix-email-list.xml',
                               {
                                   'stix_email_list': stix_email_list,
                                   'description' : self.cleaned_data['desc']
                                })
        cb = tm11.ContentBlock(t.CB_STIX_XML_101, xml)
        return cb

yeti_client/views.py
from multiprocessing import Process

from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, redirect
from django.template import RequestContext

from forms import ConfigForm, PushStixIPForm, PushStixEmailForm, PushFileForm
from models import Config, ReceivedFile, Event, RECEIVED_FILES_DIR
from utils import check_request_file, parse_status_response


poll_timestamp = ''

@login_required
def index(request, file_form=None, stix_ip_form=None, stix_email_form=None):
    if request.is_ajax():
        template = "index_poll_ajax.html"
    else:
        template = "index.html"

    config = Config.objects.get()

    try:
        received_files = ReceivedFile.objects.all()
    except ObjectDoesNotExist:
        received_files = []

    return render(request, template,
        {
            'file_form': file_form or PushFileForm(),
            'stix_ip_form': stix_ip_form or PushStixIPForm(),
            'stix_email_form': stix_email_form or PushStixEmailForm(),
            'polling': config.polling,
            'poll_rate': config.pollRate * 1000,
            'received_files': received_files,
            'received_files_dir': RECEIVED_FILES_DIR,
            'poll_timestamp': config.poll_req_tstamp
        }, context_instance=RequestContext(request))

@login_required
def history(request):
    event_history = Event.objects.all()
    return render(request, 'history.html', {'event_history': event_history})

@login_required
def alerts(request):
    return render(request, 'alerts.html')

@login_required
@permission_required('user.is_superuser', raise_exception=True)
def settings(request):
    if request.method == 'POST':
        config = Config.objects.get()
        request.FILES['privFile'] = check_request_file('privFile', request, config.privFile)
        request.FILES['pubFile'] = check_request_file('pubFile', request, config.pubFile)
            
        config_form = ConfigForm(request.POST, request.FILES)
        
        if config_form.is_valid():
            config_form.save()
            config_form = ConfigForm(instance=Config.objects.get())
            messages.info(request, 'Settings saved')
        else:
            messages.info(request, 'Invalid form')
    else:
        config_form = ConfigForm(instance=Config.objects.get())

    return render(request, 'settings.html', {'config_form': config_form})

@login_required
def push_file(request):
    if request.method == 'POST':
        push_file_form = PushFileForm(request.POST, request.FILES)
        if push_file_form.is_valid():
            f = request.FILES['content_file']
            cb = push_file_form.get_content_block(f)

            config = Config.objects.get()
            resp = config.call_inbox(cb)
            config.push_event(request.user.username, resp.status_type, 'File: ' + f.name)
            messages.info(request, parse_status_response(resp))
        else:
            messages.info(request, 'Invalid form')
            return index(request, push_file_form=push_file_form)
    # end if

    return redirect('index')

@login_required
def push_stix_ip(request):
    if request.method == 'POST':
        stix_form = PushStixIPForm(request.POST)
        if stix_form.is_valid():
            cb = stix_form.get_content_block()
            config = Config.objects.get()
            resp = config.call_inbox(cb)
            config.push_event(request.user.username, resp.status_type,
                              '[STIX] IP List:\n' + request.POST['ip_list'] + '\nDescription:\n' + request.POST['desc'])
            messages.info(request, parse_status_response(resp))
        else:
            messages.info(request, 'Invalid form')
            return index(request, stix_ip_form=stix_form)
    # end if

    return redirect('index')

@login_required
def push_stix_email(request):
    if request.method == 'POST':
        stix_form = PushStixEmailForm(request.POST)
        if stix_form.is_valid():
            cb = stix_form.get_content_block()
            config = Config.objects.get()
            resp = config.call_inbox(cb)
            config.push_event(request.user.username, resp.status_type,
                              '[STIX] E-mail List:\n' + request.POST['email_list'] + '\nDescription:\n' + request.POST['desc'])
            messages.info(request, parse_status_response(resp))
        else:
            messages.info(request, 'Invalid form')
            return index(request, stix_email_form=stix_form)
    # end if

    return redirect('index')


polling_process = None

@login_required
def pull(request):
    global polling_process

    if request.method == 'POST':
        config = Config.objects.get()

        if not config.polling:
            polling_process = Process(target=config.poll_request)
            polling_process.start()
            config.polling = True
            config.save()
            messages.info(request, 'Polling started')
        else:
            polling_process.terminate()
            config.polling = False
            config.save()
            messages.info(request, 'Polling stopped')
    # end if

    return redirect('index')

yeti_client/templates/alerts.html
{% include "header.html" %}

<iframe src="http://localhost/#/dashboard/file/default.json" width="100%" height="500" seamless></iframe>

{% include "footer.html" %}

yeti_client/templates/footer.html
<p><br/><div id="logo"></div></p>

</body>
</html>

yeti_client/templates/header.html
<!DOCTYPE html>
<html>

{% load staticfiles %}

<head lang="en">
    <meta charset="UTF-8">
    <title>{{ CLIENT_NAME }} v{{ VERSION }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <script src="{% static 'jquery-2.1.1.min.js' %}"></script>
</head>

<body>
<span><a href="{% url 'index' %}"><img src="{% static 'yeti.png' %}" /></a></span>
<span id="header">{{ CLIENT_NAME }} </span>
<span id="version">v{{ VERSION }}</span>
{% if user.is_authenticated %}
<p><div id="menu">
    <a href="{% url 'index' %}">Home</a> |
    <a href="{% url 'history' %}">Event Log</a> |
    {% if ENABLE_ALERT_VIEWER %}
    <a href="{% url 'alerts' %}">Alert Viewer</a> |
    {% endif %}
    {% if user.is_superuser %}
    <a href="{% url 'settings' %}">Settings</a> |
    {% endif %}
    <a href="{% url 'logout' %}">Logout</a>
</div></p>
{% endif %}

<hr />

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

yeti_client/templates/history.html
{% include "header.html" %}

<h2>Event Log</h2>

<table id="list">
    <thead>
        <tr>
            <th>Timestamp</th>
            <th>User</th>
            <th>Server</th>
            <th>Collection</th>
            <th>Operation</th>
            <th>Result</th>
            <th>Contents</th>
        </tr>
    </thead>
    <tbody>
    {% for e in event_history %}
        <tr>
            <td>{{ e.timestamp|date:"Y-m-d\TH:i:s" }}</td>
            <td>{{ e.user }}</td>
            <td>{{ e.server }}</td>
            <td>{{ e.collection }}</td>
            <td>{{ e.operation }}</td>
            <td>{{ e.result }}</td>
            <td>{{ e.contents|linebreaksbr }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% include "footer.html" %}

yeti_client/templates/index.html
{% include "header.html" %}

{% if polling %}
<script>
    $(document).ready(function() {
        setInterval( function() {
            $("#received-files").load("{% url 'index' %}"); }, {{ poll_rate }});
    });
</script>
{% endif %}

<h2>Push to the TAXII Server</h2>

<h3>Document (File Upload)</h3>

<form enctype="multipart/form-data" method="POST" action="{% url 'push_file' %}">
    {% csrf_token %}
    {{ file_form.as_p }}
    <p><input type="submit" value="Push File" /></p>
</form>

<h3>IP List (STIX)</h3>

<form method="POST" action="{% url 'push_stix_ip' %}">
    {% csrf_token %}
    <table id="ywc-table">
        {{ stix_ip_form.as_table }}
    </table>
    <div style="font-size: 0.8em">Example: 192.168.0.5, 10.0.0.42</div>
    <p><input type="submit" value="Push IP List" /></p>
</form>

<h3>E-mail List (STIX)</h3>

<form method="POST" action="{% url 'push_stix_email' %}">
    {% csrf_token %}
    <table id="ywc-table">
        {{ stix_email_form.as_table }}
    </table>
    <div style="font-size: 0.8em">Example: foo@example.com, bar@example.com</div>
    <p><input type="submit" value="Push E-mail List" /></p>
</form>

<hr />

<h2>Pull from TAXII Server</h2>

<form method="POST" action="{% url 'pull' %}">
    {% csrf_token %}
    {% if polling %}
        <p><input type="submit" value="Stop Polling" /></p>
    {% else %}
        <p><input type="submit" value="Start Polling" /></p>
    {% endif %}
</form>
<table id="list">
    <thead>
        <tr>
            <th>Timestamp</th>
            <th>Filename</th>
            <th>Server</th>
            <th>Collection</th>
        </tr>
    </thead>
    <tbody id="received-files">
        {% include "index_poll_ajax.html" %}
    </tbody>
</table>

{% include "footer.html" %}

yeti_client/templates/index_poll_ajax.html
    <tr>
        <td colspan="4">Last poll at: {{ poll_timestamp|date:"D j F Y H:i.s T" }}</td>
    </tr>
{% for f in received_files %}
    <tr>
        <td>{{ f.timestamp|date:"Y-m-d\TH:i:s" }}</td>
        <td><a href="{{ settings.MEDIA_URL }}received/{{ f.filename }}">{{ f.filename }}</a></td>
        <td>{{ f.server }}</td>
        <td>{{ f.collection }}</td>
    </tr>
{% endfor %}

yeti_client/templates/login.html
{% include "header.html" %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="POST" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="Log In" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{% include "footer.html" %}

yeti_client/templates/settings.html
{% include "header.html" %}

<h2>Settings</h2>

<form enctype="multipart/form-data" method="POST" action="{% url 'settings' %}">
    {% csrf_token %}
    {{ config_form.non_field_errors }}
    <table id="ywc-table">
        {{ config_form.as_table }}
        <tr>
            <td>&nbsp;</td>
            <td><input type="submit" value="Save" />
            <input type="reset" value="Reset" /></td>
        </tr>
    </table>
</form>

{% include "footer.html" %}

yeti_client/templates/stix.html
{% include "header.html" %}

<h1>STIX Data Push Examples</h1>

<h2>Push an IP List</h2>

<form enctype="multipart/form-data" method="POST" action="{% url 'push_stix' %}">
    {% csrf_token %}
    {{ push_stix_form.non_field_errors }}
    {{ push_stix_form.ip_list.errors }}
    <label for="id_ip_list">List of IP addresses: </label>
    {{ push_stix_form.ip_list }}
    <span style="font-size: 0.8em">(Example, 192.168.0.5, 10.0.0.42)</span>
    <p><input type="submit" value="Push IP List" /></p>
</form>

{% include "footer.html" %}